# Оператор `raise` в Python

# Оператор `raise` используется для возбуждения исключений, что позволяет контролировать
# поведение программы при возникновении ошибок или непредвиденных ситуаций.

### Стандартные исключения

В Python встроены стандартные классы исключений, такие как `ValueError`, `TypeError`, `ZeroDivisionError` и другие. Они позволяют обрабатывать различные типы ошибок.

#### Пример использования `ValueError`

Возбудим исключение `ValueError`, если значение `b` равно нулю:


```python
def divide(a, b):
    """
    Функция делит число a на число b.
    
    :param a: Деленое число
    :type a: int or float
    :param b: Делитель
    :type b: int or float
    :return: Результат деления
    :rtype: float
    :raises ValueError: Если b равно 0
    """
    if b == 0:
        raise ValueError("Деление на ноль недопустимо")
    return a / b
```

Теперь попробуем обработать это исключение с помощью блока `try-except`:


```python
try:
    result = divide(10, 0)
except ValueError as e:
    print(e)
```

    Деление на ноль недопустимо
    

### Пользовательские исключения

Иногда стандартных исключений недостаточно, и нужно создать свои собственные классы исключений для специфичных случаев.

#### Пример создания пользовательского исключения

Создадим класс `MyCustomException`, который наследуется от базового класса `Exception`:


```python
class MyCustomException(Exception):
    """Пользовательское исключение для обработки особых ошибок."""

    def __init__(self, message, code):
        """
        Конструктор класса MyCustomException.
        
        :param message: Сообщение об ошибке
        :type message: str
        :param code: Код ошибки
        :type code: int
        """
        super().__init__(message)
        self.code = code  # Дополнительный атрибут для хранения кода ошибки
```

Теперь возбудим наше пользовательское исключение с дополнительной информацией:


```python
def process_data(data):
    """
    Функция обрабатывает данные.
    
    :param data: Список данных
    :type data: list
    :raises MyCustomException: Если список пуст
    """
    if not data:
        raise MyCustomException("Пустые данные обнаружены", code=400)
```

Обработаем пользовательское исключение:


```python
try:
    data = []
    process_data(data)
except MyCustomException as e:
    print(f"{e} - Код ошибки: {e.code}")
```

    Пустые данные обнаружены - Код ошибки: 400
    

### Заключение

Использование оператора `raise` делает ваш код более понятным и управляемым, а также улучшает взаимодействие с пользователями программы благодаря точной передаче информации об ошибках. Документация исключений помогает другим разработчикам понять, какие ошибки могут возникнуть, и правильно их обработать, тем самым повышая надёжность и стабильность программы.
